
# 使用application的配置文件
spring:
  # 配置文件 dev|test|prod
  profiles:
    active: dev

# mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:mappering/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.liang.modules.sys.entity
  global-config:
    db-config:
      table-underline: true
      db-type: mysql